#!/bin/sh

battery=$1
status=$(upower -i "/org/freedesktop/UPower/devices/battery_${battery}" | grep -E "state" | awk '{print($2)}')
percent=$(upower -i "/org/freedesktop/UPower/devices/battery_${battery}" | grep -E "percentage" | awk '{print($2)}')

full_text="";

if [ "$status" == "discharging" ]; then
	full_text="⚡ ${percent} Bat";
elif [ "$status" == "charging" ]; then
	full_text=" ${percent} Chr";
else
	full_text="⚡ ${percent}";
fi

echo $full_text
